using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdventureGame;

public class ItemContainer
{
    Random _random = new Random();

    public List<Item> noItems;
    public List<Item> items1;
    public List<Item> items2;
    public List<Item> items3;
    public List<Item> items4;
    public List<Item> items5;
    public List<Item> items6;

    public List<Item> weakAmulets;
    public List<Item> magicAmulets;
    public List<Item> rareAmulets;

    public ItemContainer()
    {
        noItems = new List<Item>();
        items1 = new List<Item>();
        items2 = new List<Item>();
        items3 = new List<Item>();
        items4 = new List<Item>();
        items5 = new List<Item>();
        items6 = new List<Item>();

        weakAmulets = new List<Item>();
        magicAmulets = new List<Item>();
        rareAmulets = new List<Item>();
        AddItemsToList();
    }

    public void AddItemsToList()
    {
        // WEAPONS string name, type, int damage, int strength, int fireDamage, int poisonDamage, int skillLevel, int lifesteal int strengthRequirement, int levelRequirement
        Item item1a = new("Axe", ItemType.WeaponRightHand, 1, 0, 0, 0, 0, 0, 2, 2);
        Item item2a = new("Sword", ItemType.WeaponRightHand, 2, 0, 0, 0, 0, 0, 3, 3);
        Item item3a = new("Blood Spear", ItemType.WeaponRightHand, 2, 0, 0, 0, 0, 5, 8, 1);
        Item item4a = new("Pike", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 2, 5, 6);
        Item item5a = new("Small Knife", ItemType.WeaponRightHand, 2, 2, 0, 0, 0, 0, 0, 2);
        Item item6a = new("Spear", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 0, 5, 3);
        RandomItem item7 = new("Normal Axe", ItemType.WeaponRightHand);
        RandomItem item8 = new("Normal Sword", ItemType.WeaponRightHand);
        RandomItem item9 = new("Normal Hammer", ItemType.WeaponRightHand);

        Item item7a = new("Scythe", ItemType.WeaponRightHand, 4, 1, 0, 0, 0, 2, 5, 4);
        Item item8a = new("Hammer", ItemType.WeaponRightHand, 5, 0, 0, 0, 0, 0, 8, 6);
        Item item9a = new("Blood Knife", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 8, 8, 6);
        Item item10a = new("Blood Sword", ItemType.WeaponRightHand, 4, 0, 0, 0, 0, 6, 8, 6);

        Item item11a = new("Shiny Axe", ItemType.WeaponRightHand, 6, 2, 0, 0, 0, 0, 10, 10);
        RandomItem item12a = new("Bloody Hook", ItemType.WeaponLeftHand);
        RandomItem item13a = new("Magic Hook", ItemType.WeaponLeftHand, ItemQuality.Magic);
        Item item25a = new("Hook", ItemType.WeaponLeftHand, 2, 0, 0, 0, 0, 5, 11, 12);

        // ARMORS string name, type, health, regen, CritChance, strength, dodgeChance, armor, skillLevel, lifesteal, strengthRequirement, levelRequirement
        Item item1b = new("Rusty Armor", ItemType.Armor, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1);
        Item item2b = new("Cloak", ItemType.Armor, 0, 0, 0, 0, 5, 2, 0, 0, 2, 3);
        Item item3b = new("Rags", ItemType.Armor, 5, 0, 0, 0, 0, 0, 0, 0, 0, 2);
        Item item4b = new("Boots", ItemType.Boots, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2);
        Item item5b = new("Sandals", ItemType.Boots, 0, 0, 0, 0, 8, 0, 0, 0, 0, 2);
        Item item6b = new("Gloves", ItemType.Gloves, 0, 0, 0, 1, 0, 1, 0, 0, 1, 4);
        Item item7b = new("Leather Gloves", ItemType.Gloves, 11, 0, 0, 0, 0, 1, 0, 0, 0, 5);
        Item item8b = new("Health Boots", ItemType.Boots, 0, 2, 0, 0, 0, 0, 0, 0, 3, 3);
        Item item9b = new("Rusty Boots", ItemType.Boots, 5, 1, 3, 1, 1, 0, 0, 0, 3, 3);
        Item item10 = new("Strength Boots", ItemType.Boots, 15, 0, 7, 2, 0, 0, 0, 0, 2, 5);
        Item item11 = new("Heavy Armor", ItemType.Armor, 15, 0, 0, 1, 0, 1, 0, 0, 0, 2);
        Item item12 = new("Vanity Gloves", ItemType.Gloves, 0, 0, 2, 1, 0, 0, 0, 0, 3, 3);
        Item item13 = new("Vanity Boots", ItemType.Boots, 0, 0, 0, 2, 2, 0, 0, 0, 3, 2);
        Item item14 = new("Leather Boots", ItemType.Boots, 11, 0, 0, 0, 0, 0, 0, 0, 3, 5);
        RandomItem item15 = new("Normal Gloves", ItemType.Gloves);
        RandomItem item16 = new("Normal Boots", ItemType.Boots);
        RandomItem item17 = new("Normal Belt", ItemType.Belt);
        RandomItem item18 = new("Normal Armor", ItemType.Armor);
        RandomItem item19 = new("Normal Leggings", ItemType.Leggings);
        RandomItem item20 = new("Normal Gauntlets", ItemType.Gloves);
        RandomItem item21 = new("Normal Plate", ItemType.Armor);
        RandomItem item22 = new("Normal Mitts", ItemType.Gloves);
        RandomItem item23 = new("Armor", ItemType.Armor);
        RandomItem item24 = new("Leggings", ItemType.Leggings);
        RandomItem item25 = new("Pants", ItemType.Leggings);
        RandomItem item26 = new("Gauntlets", ItemType.Gloves);
        RandomItem item27 = new("Normal Sandals", ItemType.Boots);
        RandomItem item28 = new("Torn Pants", ItemType.Leggings);
        RandomItem item29 = new("Rusty Belt", ItemType.Belt);
        RandomItem item30 = new("Leather Belt", ItemType.Belt);
        RandomItem item31 = new("Torn Sandals", ItemType.Boots);
        RandomItem item32 = new("Shoulders", ItemType.Shoulders);
        Item item33 = new("Pads", ItemType.Shoulders, 6, 0, 0, 0, 1, 0, 0, 0, 3, 2);
        Item item34 = new("Strong Shoulders", ItemType.Shoulders, 0, 1, 0, 2, 0, 1, 0, 0, 3, 2);
        Item item35 = new("Strong Belt", ItemType.Belt, 2, 0, 0, 1, 0, 0, 0, 0, 0, 4);


        Item item10b = new("Bronze Boots", ItemType.Boots, 0, 2, 0, 6, 6, 3, 0, 0, 7, 2);
        Item item11b = new("Swift Boots", ItemType.Boots, 10, 0, 10, 0, 7, 3, 0, 0, 7, 3);
        Item item12b = new("Plate", ItemType.Armor, 0, 0, 5, 3, 0, 3, 0, 0, 5, 3);
        Item item13b = new("Bronze Plate", ItemType.Armor, 20, 0, 2, 3, 2, 3, 0, 0, 5, 6);
        Item item14b = new("Rusty Plate", ItemType.Armor, 0, 1, 2, 3, 2, 4, 0, 0, 9, 6);
        Item item15b = new("Bronze Gloves", ItemType.Gloves, 0, 0, 8, 2, 0, 2, 0, 0, 5, 6);

        Item item16b = new("Vampire Leggings", ItemType.Leggings, 20, 1, 4, 0, 0, 2, 0, 10, 8, 9);
        Item item17b = new("Vampire Gloves", ItemType.Gloves, 10, 1, 0, 2, 0, 1, 0, 10, 5, 6);
        RandomItem item18b = new("Magic Leggings", ItemType.Leggings, ItemQuality.Magic);
        RandomItem item19b = new("Magic Armor", ItemType.Armor, ItemQuality.Magic);
        RandomItem item20b = new("Magic Pants", ItemType.Leggings, ItemQuality.Magic);
        RandomItem item21b = new("Magic Plate", ItemType.Armor, ItemQuality.Magic);
        RandomItem item22b = new("Magic Gloves", ItemType.Gloves, ItemQuality.Magic);
        RandomItem item23b = new("Magic Belt", ItemType.Belt, ItemQuality.Magic);
        RandomItem item24b = new("Magic Helmet", ItemType.Helmet, ItemQuality.Magic);
        RandomItem item26b = new("Magic Mitts", ItemType.Gloves, ItemQuality.Magic);
        RandomItem item27b = new("Vampire Belt", ItemType.Belt, ItemQuality.Magic);
        RandomItem item28b = new("Magic Great Helm", ItemType.Helmet, ItemQuality.Magic);
        Item item29b = new("Vampire Hook", ItemType.WeaponLeftHand, 1, 0, 0, 0, 0, 11, 7, 13);
        RandomItem item30b = new("Magic Boots", ItemType.Boots, ItemQuality.Magic);
        RandomItem item31b = new("Magic Sandals", ItemType.Boots, ItemQuality.Magic);
        RandomItem item32b = new("Shoulder Guards", ItemType.Boots);

        // AMULETS Normal/noPrefix
        Amulet amulet1a = new("Mystic Amulet");
        Amulet amulet2a = new("Mysterious Amulet");
        Amulet amulet3a = new("Millennium Amulet");
        // AMULETS Magic
        Amulet amulet1b = new("Magic Amulet", "Magic");
        // AMULETS Rare
        Amulet amulet1c = new("Shiny Amulet", "Rare");
        Amulet amulet2c = new("Rare Amulet", "Rare");
        Amulet amulet3c = new("Golden Amulet", "Rare");
        Amulet amulet4c = new("Sparkling Amulet", "Rare");

        // List of items 1
        noItems.Add(null);
        items1.Add(item1a);
        items1.Add(item2a);
        items1.Add(item1b);
        items1.Add(item6b);
        items1.Add(item12);
        items1.Add(item13);
        items1.Add(item14);
        items1.Add(item20);
        items1.Add(item26);
        items1.Add(item27);
        items1.Add(item28);
        items1.Add(item29);
        items1.Add(item34);
        items1.Add(null); 
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null); 
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null); 
        items1.Add(null);
        items1.Add(null);

        // List of items 2
        items2.Add(item1b);
        items2.Add(item2b);
        items2.Add(item3b);
        items2.Add(item4b);
        items2.Add(item5b);
        items2.Add(item7b);
        items2.Add(item8b);
        items2.Add(item9b);
        items2.Add(item1a);
        items2.Add(item3a);
        items2.Add(item4a);
        items2.Add(item5a);
        items2.Add(item6a);
        items2.Add(item10);
        items2.Add(item11);
        items2.Add(item14);
        items2.Add(item9a);
        items2.Add(item10a);
        items2.Add(item7);
        items2.Add(item8);
        items2.Add(item15);
        items2.Add(item16);
        items2.Add(item17);
        items2.Add(item18);
        items2.Add(item19);
        items2.Add(item20);
        items2.Add(item21);
        items2.Add(item22); 
        items2.Add(item28);
        items2.Add(item29);
        items2.Add(item9);
        items2.Add(item30);
        items2.Add(item33);
        items2.Add(item35);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null); 
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);

        // List of items 3 SNOW
        items3.Add(item6a);
        items3.Add(item7a);
        items3.Add(item8a);
        items3.Add(item2b);
        items3.Add(item10b);
        items3.Add(item11b);
        items3.Add(item12b);
        items3.Add(item13b);
        items3.Add(item14b);
        items3.Add(item15b);
        items3.Add(item7);
        items3.Add(item8);
        items3.Add(item15);
        items3.Add(item19);
        items3.Add(item18b);
        items3.Add(item24);
        items3.Add(item25); 
        items3.Add(item22);
        items3.Add(item9);
        items3.Add(item30);
        items3.Add(item31);
        items3.Add(item34);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null); 
        items3.Add(null);
        items3.Add(null);

        // List of items 4 SEA Act 3
        items4.Add(item16b);
        items4.Add(item17b);
        items4.Add(amulet1b);
        items4.Add(item11a);
        items4.Add(item18b);
        items4.Add(item19b);
        items4.Add(item20b);
        items4.Add(item21b);
        items4.Add(item12a);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null); 
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);

        // List of items 5 Act 4 west weak
        items5.Add(item21b);
        items5.Add(item22b);
        items5.Add(item23b);
        items5.Add(item24b);
        items5.Add(item25a);
        items5.Add(item26b);
        items5.Add(item27b);
        items5.Add(item28b);
        items5.Add(item29b);
        items5.Add(item30b);
        items5.Add(item31b);
        items5.Add(item32b);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);

        // List of Items Dragons Act4
        items6.Add(amulet1c);
        items6.Add(amulet2c);
        items6.Add(amulet3c);
        items6.Add(amulet4c);
        items6.Add(item13a);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);

        // List of weak amulets
        weakAmulets.Add(amulet1a);
        weakAmulets.Add(amulet2a);
        weakAmulets.Add(amulet3a);
        weakAmulets.Add(null);
        weakAmulets.Add(null);
        weakAmulets.Add(null);
        // List of magic amulets
        magicAmulets.Add(amulet1b);
        // List of rare amulets
        rareAmulets.Add(amulet1c);
    }

}