using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AdventureGame;

public class ItemContainer
{
    Random _random = new Random();

    public List<Item> noItems;
    public List<Item> items1;
    public List<Item> items2;
    public List<Item> items3;
    public List<Item> items4;
    public List<Item> items5;
    public List<Item> items6;
    public List<Item> items7;
    public List<Item> items8;
    public List<Item> godlyBossItems;

    public List<Item> weakAmulets;
    public List<Item> magicAmulets;
    public List<Item> rareAmulets;

    public ItemContainer()
    {
        noItems = new List<Item>();
        items1 = new List<Item>();
        items2 = new List<Item>();
        items3 = new List<Item>();
        items4 = new List<Item>();
        items5 = new List<Item>();
        items6 = new List<Item>();
        items7 = new List<Item>();
        items8 = new List<Item>();
        godlyBossItems = new List<Item>();

        weakAmulets = new List<Item>();
        magicAmulets = new List<Item>();
        rareAmulets = new List<Item>();
        AddItemsToList();
    }

    public void AddItemsToList()
    {
        // WEAPONS string name, type, damage, strength, fireDamage, poisonDamage, skillLevel, lifesteal, CritDmg, strengthRequirement, levelRequirement
        Item item1a = new("Axe", ItemType.WeaponRightHand, 1, 0, 0, 0, 0, 0, 0, 2, 2);
        Item item2a = new("Sword", ItemType.WeaponRightHand, 2, 0, 0, 0, 0, 0, 0, 3, 3);
        Item item3a = new("Blood Spear", ItemType.WeaponRightHand, 2, 0, 0, 0, 0, 12, 0, 8, 1);
        Item item4a = new("Pike", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 2, 0, 5, 6);
        Item item5a = new("Small Knife", ItemType.WeaponRightHand, 2, 2, 0, 0, 0, 0, 0, 0, 2);
        Item item6a = new("Spear", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 0, 0, 5, 3);
        Item item7aa = new("Whip", ItemType.WeaponRightHand, 1, 0, 0, 0, 0, 1, 10, 4, 2);
        Item item8aa = new("Rusty Dagger", ItemType.WeaponRightHand, 1, 0, 0, 0, 0, 0, 0, 0, 4);
        RandomItem item7 = new("Normal Axe", ItemType.WeaponRightHand);
        RandomItem item8 = new("Normal Sword", ItemType.WeaponRightHand);
        RandomItem item9 = new("Normal Hammer", ItemType.WeaponRightHand);
        Item item10c = new("Knife", ItemType.WeaponRightHand, 1, 0, 0, 0, 0, 0, 0, 3, 3);
        RandomItem item11c = new("Small Sword", ItemType.WeaponRightHand);
        RandomItem item12c = new("Small Hammer", ItemType.WeaponRightHand);
        Item item13c = new("Dagger", ItemType.WeaponRightHand, 1, 0, 0, 0, 0, 1, 1, 4, 3);
        RandomItem item14c = new("Small Dagger", ItemType.WeaponRightHand);
        RandomItem item15d = new("Halberd", ItemType.WeaponRightHand);
        RandomItem item16d = new("Bloody Dagger", ItemType.WeaponRightHand);
        Item item17d = new("Rapier", ItemType.WeaponRightHand, 0, 0, 7, 0, 0, 0, 0, 0, 20, 0, 3);
        Item item18d = new("Bloody Axe", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 6, 10, 5, 6);

        Item item7a = new("Scythe", ItemType.WeaponRightHand, 4, 1, 0, 0, 0, 2, 0, 5, 8);
        Item item8a = new("Hammer", ItemType.WeaponRightHand, 5, 0, 0, 0, 0, 0, 0, 8, 9);
        Item item9a = new("Blood Knife", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 8, 0, 8, 6);
        Item item10a = new("Blood Sword", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 6, 0, 8, 6);
        Item item10aa = new("Vampire Slayer", ItemType.WeaponRightHand, 3, 0, 0, 0, 0, 15, 0, 7, 11);

        Item item11a = new("Shiny Axe", ItemType.WeaponRightHand, 6, 2, 0, 0, 0, 0, 0, 10, 15);
        RandomItem item12a = new("Bloody Hook", ItemType.WeaponLeftHand);
        RandomItem item13a = new("Magic Hook", ItemType.WeaponLeftHand, ItemQuality.Magic);
        Item item25a = new("Hook", ItemType.WeaponLeftHand, 2, 0, 0, 0, 0, 5, 0, 11, 12);
        RandomItem item26a = new("Magic Sword", ItemType.WeaponRightHand, ItemQuality.Magic);
        RandomItem item27a = new("Magic Hammer", ItemType.WeaponRightHand, ItemQuality.Magic);
        RandomItem item28a = new("Magic Halberd", ItemType.WeaponRightHand, ItemQuality.Magic);
        RandomItem item29aa = new("Lance", ItemType.WeaponRightHand, ItemQuality.Magic);
        RandomItem item30aa = new("Bronze Clever", ItemType.WeaponRightHand, ItemQuality.Magic);

        RandomItem item29a = new("Great Halberd", ItemType.WeaponRightHand, ItemQuality.Epic);
        RandomItem item30a = new("Great Sword", ItemType.WeaponRightHand, ItemQuality.Epic);

        // ARMORS string name, type, health, regen, CritChance, strength, dodgeChance, armor, skillLevel, lifesteal, critdmg, strengthRequirement, levelRequirement
        Item item1b = new("Rusty Armor", ItemType.Armor, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1);
        Item item2b = new("Cloak", ItemType.Armor, 0, 0, 0, 0, 6, 2, 0, 0, 0, 2, 3);
        Item item3b = new("Rags", ItemType.Armor, 5, 0, 0, 0, 7, 0, 0, 0, 0, 0, 2);
        Item item4b = new("Boots", ItemType.Boots, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2);
        Item item5b = new("Sandals", ItemType.Boots, 0, 0, 0, 1, 10, 0, 0, 0, 0, 0, 2);
        Item item6b = new("Gloves", ItemType.Gloves, 0, 0, 0, 1, 4, 1, 0, 0, 0, 1, 4);
        Item item7b = new("Leather Gloves", ItemType.Gloves, 11, 0, 0, 0, 0, 1, 0, 0, 0, 0, 5);
        Item item8b = new("Health Boots", ItemType.Boots, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 3);
        Item item9b = new("Rusty Boots", ItemType.Boots, 7, 1, 3, 1, 1, 0, 0, 0, 0, 3, 3);
        Item item10 = new("Strength Boots", ItemType.Boots, 13, 0, 4, 2, 0, 0, 0, 0, 0, 2, 5);
        Item item11 = new("Heavy Armor", ItemType.Armor, 15, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2);
        Item item12 = new("Damaged Gloves", ItemType.Gloves, 0, 0, 2, 1, 0, 0, 0, 0, 0, 3, 3);
        Item item13 = new("Damaged Boots", ItemType.Boots, 0, 0, 0, 2, 2, 0, 0, 0, 0, 3, 2);
        Item item14 = new("Leather Boots", ItemType.Boots, 11, 1, 0, 1, 8, 0, 0, 0, 0, 3, 5);
        Item item15bb = new("Damaged Armor", ItemType.Armor, 12, 0, 0, 0, 7, 0, 0, 0, 0, 0, 4);
        Item item16bb = new("Rusty Mail", ItemType.Armor, 0, 0, 0, 0, 5, 1, 0, 0, 0, 0, 4);
        Item item17bb = new("Leather Armor", ItemType.Armor, 15, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3);
        Item item18bb = new("Leather Helmet", ItemType.Helmet, 10, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2);
        Item item19bb = new("Worn Gloves", ItemType.Gloves, 0, 0, 0, 0, 3, 1, 0, 0, 0, 3, 3);
        Item item20bb = new("Worn Pants", ItemType.Leggings, 14, 0, 0, 0, 4, 0, 0, 0, 0, 0, 4);
        RandomItem item15 = new("Normal Gloves", ItemType.Gloves);
        RandomItem item16 = new("Normal Boots", ItemType.Boots);
        RandomItem item17 = new("Normal Belt", ItemType.Belt);
        RandomItem item18 = new("Normal Armor", ItemType.Armor);
        RandomItem item19 = new("Normal Leggings", ItemType.Leggings);
        RandomItem item20 = new("Normal Gauntlets", ItemType.Gloves);
        RandomItem item21 = new("Normal Plate", ItemType.Armor);
        RandomItem item22 = new("Normal Mitts", ItemType.Gloves);
        RandomItem item23 = new("Armor", ItemType.Armor);
        RandomItem item24 = new("Leggings", ItemType.Leggings);
        RandomItem item25 = new("Pants", ItemType.Leggings);
        RandomItem item26 = new("Gauntlets", ItemType.Gloves);
        RandomItem item27 = new("Normal Sandals", ItemType.Boots);
        RandomItem item28 = new("Torn Pants", ItemType.Leggings);
        RandomItem item29 = new("Rusty Belt", ItemType.Belt);
        RandomItem item30 = new("Leather Belt", ItemType.Belt);
        RandomItem item31 = new("Torn Sandals", ItemType.Boots);
        RandomItem item32 = new("Shoulders", ItemType.Shoulders);
        Item item33 = new("Pads", ItemType.Shoulders, 6, 0, 0, 0, 1, 0, 0, 0, 0, 3, 2);
        Item item34 = new("Strong Shoulders", ItemType.Shoulders, 0, 0, 0, 2, 0, 1, 0, 0, 0, 3, 2);
        Item item35 = new("Strong Belt", ItemType.Belt, 2, 0, 0, 1, 3, 0, 0, 0, 0, 0, 4);
        Item item36 = new("Belt", ItemType.Belt, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2);
        RandomItem item37 = new("Normal Shoes", ItemType.Boots);
        Item item38 = new("Iron Boots", ItemType.Boots, 2, 1, 0, 0, 3, 2, 0, 0, 0, 4, 4);
        Item item39 = new("Iron Leggings", ItemType.Leggings, 20, 0, 0, 0, 1, 1, 0, 0, 0, 7, 10);
        Item item40 = new("Iron Shoulders", ItemType.Shoulders, 18, 0, 3, 0, 2, 1, 0, 0, 0, 8, 9);
        Item item41 = new("Strong Pads", ItemType.Shoulders, 4, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2);
        Item item42 = new("Belt of Life", ItemType.Belt, 25, 2, 0, 0, 1, 0, 0, 0, 0, 0, 8);
        RandomItem item43 = new("Old Boots", ItemType.Boots);
        RandomItem item44 = new("Plated Jacket", ItemType.Armor);
        RandomItem item45 = new("Steel Gauntlets", ItemType.Gloves);
       

        Item item10b = new("Bronze Boots", ItemType.Boots, 0, 2, 0, 3, 2, 3, 0, 0, 0, 7, 2);
        Item item11b = new("Swift Boots", ItemType.Boots, 10, 0, 5, 0, 7, 2, 0, 0, 0, 7, 3);
        Item item12b = new("Plate", ItemType.Armor, 0, 0, 5, 3, 6, 2, 0, 0, 0, 5, 3);
        Item item13b = new("Bronze Plate", ItemType.Armor, 20, 0, 2, 1, 2, 2, 0, 0, 0, 5, 6);
        Item item14b = new("Rusty Plate", ItemType.Armor, 0, 1, 2, 3, 2, 2, 0, 0, 0, 9, 6);
        Item item15b = new("Bronze Gloves", ItemType.Gloves, 0, 0, 8, 2, 0, 2, 0, 0, 0, 5, 6);
        RandomItem item16c = new("Rusty Shoulders", ItemType.Shoulders);
        Item item17c = new("Veil of Evasion", ItemType.Helmet, 0, 4, 0, 0, 7, 0, 0, 0, 0, 10, 13);
        Item item18c = new("Bronze Leggings", ItemType.Leggings, 0, 4, 0, 0, 8, 2, 0, 0, 0, 11, 11);
        Item item19c = new("Bronze Belt", ItemType.Belt, 0, 0, 0, 0, 9, 1, 0, 0, 0, 7, 12);

        Item item16b = new("Vampire Leggings", ItemType.Leggings, 20, 1, 4, 0, 0, 2, 0, 10, 0, 8, 9);
        Item item17b = new("Vampire Gloves", ItemType.Gloves, 10, 1, 0, 2, 0, 1, 0, 10, 0, 5, 6);
        RandomItem item18b = new("Magic Leggings", ItemType.Leggings, ItemQuality.Magic);
        RandomItem item19b = new("Magic Armor", ItemType.Armor, ItemQuality.Magic);
        RandomItem item20b = new("Magic Pants", ItemType.Leggings, ItemQuality.Magic);
        RandomItem item21b = new("Magic Plate", ItemType.Armor, ItemQuality.Magic);
        RandomItem item22b = new("Magic Gloves", ItemType.Gloves, ItemQuality.Magic);
        RandomItem item23b = new("Magic Belt", ItemType.Belt, ItemQuality.Magic);
        RandomItem item24b = new("Magic Helmet", ItemType.Helmet, ItemQuality.Magic);
        RandomItem item26b = new("Magic Mitts", ItemType.Gloves, ItemQuality.Magic);
        RandomItem item27b = new("Vampire Belt", ItemType.Belt, ItemQuality.Magic);
        RandomItem item28b = new("Magic Great Helm", ItemType.Helmet, ItemQuality.Magic);
        Item item29b = new("Vampire Hook", ItemType.WeaponLeftHand, 1, 0, 0, 0, 0, 11, 0, 7, 13);
        RandomItem item30b = new("Magic Boots", ItemType.Boots, ItemQuality.Magic);
        RandomItem item31b = new("Magic Sandals", ItemType.Boots, ItemQuality.Magic);
        RandomItem item32b = new("Shoulder Guards", ItemType.Shoulders);
        RandomItem item33b = new("Magical Belt", ItemType.Belt, ItemQuality.Magic);

        // Magic items
        RandomItem magicHelmet1 = new("Magic Helmet", ItemType.Helmet, ItemQuality.Magic);
        RandomItem magicHelmet2 = new("Magic Mask", ItemType.Helmet, ItemQuality.Magic);
        RandomItem magicShoulders1 = new("Magic Shoulders", ItemType.Shoulders, ItemQuality.Magic);
        RandomItem magicShoulders2 = new("Magic Pauldrons", ItemType.Shoulders, ItemQuality.Magic);
        RandomItem magicShoulders3 = new("Mystic Shoulder Guards", ItemType.Shoulders, ItemQuality.Magic);
        RandomItem magicHook1 = new("Magic Hook", ItemType.WeaponLeftHand, ItemQuality.Magic);
        RandomItem magicHook2 = new("Magic Hook", ItemType.WeaponLeftHand, ItemQuality.Magic);
        RandomItem magicBoots1 = new("Magic Boots", ItemType.Boots, ItemQuality.Magic);
        RandomItem magicBoots2 = new("Magic Boots", ItemType.Boots, ItemQuality.Magic);
        RandomItem magicBoots3 = new("Magic Toes", ItemType.Boots, ItemQuality.Magic);
        RandomItem magicBoots4 = new("Magic Sandals", ItemType.Boots, ItemQuality.Magic);
        RandomItem magicBoots5 = new("Magic Sandals", ItemType.Boots, ItemQuality.Magic);
        RandomItem magicLeggings1 = new("Mystic Leggings", ItemType.Leggings, ItemQuality.Magic);
        RandomItem magicLeggings2 = new("Mystic Pants", ItemType.Leggings, ItemQuality.Magic);
        RandomItem magicArmor1 = new("Mystic Armor", ItemType.Armor, ItemQuality.Magic);
        RandomItem magicArmor2 = new("Mystic Plate", ItemType.Armor, ItemQuality.Magic);
        RandomItem magicBelt1 = new("Mystic Belt", ItemType.Belt, ItemQuality.Magic);
        RandomItem magicBelt2 = new("Mystic Ribbon", ItemType.Belt, ItemQuality.Magic);
        RandomItem magicBelt3 = new("Magic Ribbon", ItemType.Belt, ItemQuality.Magic);
        RandomItem magicGloves1 = new("Mystic Gloves", ItemType.Gloves, ItemQuality.Magic);
        RandomItem magicGloves2 = new("Mystic Gauntlets", ItemType.Gloves, ItemQuality.Magic);
        RandomItem magicWeapon1 = new("Mystic Sword", ItemType.WeaponRightHand, ItemQuality.Magic);
        RandomItem magicWeapon2 = new("Mystic Axe", ItemType.WeaponRightHand, ItemQuality.Magic);
        RandomItem magicWeapon3 = new("Mystic Lance", ItemType.WeaponRightHand, ItemQuality.Magic);
        RandomItem magicItem46 = new("Steel Shoulders", ItemType.Shoulders, ItemQuality.Magic);
        // Rare items
        RandomItem rareShoulders1 = new("Rare Shoulders", ItemType.Shoulders, ItemQuality.Rare);
        RandomItem rareShoulders2 = new("Golden Shoulders", ItemType.Shoulders, ItemQuality.Rare);
        RandomItem rareBoots1 = new("Rare Boots", ItemType.Boots, ItemQuality.Rare);
        RandomItem rareBoots2 = new("Rare Sandals", ItemType.Boots, ItemQuality.Rare);
        RandomItem item34b = new("Rare Belt", ItemType.Belt, ItemQuality.Rare);
        RandomItem item35b = new("Rare Strap", ItemType.Belt, ItemQuality.Rare);
        RandomItem item36b = new("Rare Armor", ItemType.Armor, ItemQuality.Rare);
        RandomItem item37b = new("Rare Plate", ItemType.Armor, ItemQuality.Rare);
        RandomItem item38b = new("Rare Ribbon", ItemType.Belt, ItemQuality.Rare);
        RandomItem item39b = new("Rare Gloves", ItemType.Gloves, ItemQuality.Rare);
        RandomItem item40b = new("Rare Dagger", ItemType.WeaponRightHand, ItemQuality.Rare);
        RandomItem item47 = new("Iron Jacket", ItemType.Armor, ItemQuality.Rare);
        // Epic items
        RandomItem epicSword1 = new("Epic Sword", ItemType.WeaponRightHand, ItemQuality.Epic);
        RandomItem epicSword2 = new("Epic Sword", ItemType.WeaponRightHand, ItemQuality.Epic);
        RandomItem epicGloves1 = new("Epic Gloves", ItemType.Gloves, ItemQuality.Epic);
        RandomItem epicGloves2 = new("Epic Gauntlets", ItemType.Gloves, ItemQuality.Epic);
        RandomItem epicBelt1 = new("Epic Belt", ItemType.Belt, ItemQuality.Epic);
        RandomItem epicBelt2 = new("Epic Ribbon", ItemType.Belt, ItemQuality.Epic);
        RandomItem epicBelt3 = new("Epic Sash", ItemType.Belt, ItemQuality.Epic);
        RandomItem epicLeggings1 = new("Epic Leggings", ItemType.Leggings, ItemQuality.Epic);
        RandomItem epicLeggings2 = new("Epic Pants", ItemType.Leggings, ItemQuality.Epic);
        RandomItem epicArmor1 = new("Epic Armor", ItemType.Armor, ItemQuality.Epic);
        RandomItem epicArmor2 = new("Epic Plate", ItemType.Armor, ItemQuality.Epic);
        RandomItem epicArmor3 = new("Golden Armor", ItemType.Armor, ItemQuality.Epic);
        RandomItem epicArmor4 = new("Sun Armor", ItemType.Armor, ItemQuality.Epic);
        RandomItem epicHelmet1 = new("Epic Helmet", ItemType.Helmet, ItemQuality.Epic);
        RandomItem epicHelmet2 = new("Epic Mask", ItemType.Helmet, ItemQuality.Epic);
        RandomItem epicHelmet3 = new("Epic Sallet", ItemType.Helmet, ItemQuality.Epic);
        RandomItem epicHelmet4 = new("Epic Cap", ItemType.Helmet, ItemQuality.Epic);
        RandomItem epicHook1 = new("Epic Hook", ItemType.WeaponLeftHand, ItemQuality.Epic);
        RandomItem epicHook2 = new("Epic Needle", ItemType.WeaponLeftHand, ItemQuality.Epic);
        RandomItem epicHook3 = new("Epic Fang", ItemType.WeaponLeftHand, ItemQuality.Epic);
        RandomItem epicBoots1 = new("Epic Boots", ItemType.Boots, ItemQuality.Epic);
        RandomItem epicBoots2 = new("Epic Sabatons", ItemType.Boots, ItemQuality.Epic);
        RandomItem epicShoulders1 = new("Epic Shoulders", ItemType.Shoulders, ItemQuality.Epic);
        RandomItem epicShoulders2 = new("Epic Pauldrons", ItemType.Shoulders, ItemQuality.Epic);
        // Legendary items
        RandomItem legendaryGloves = new("Legendary Gloves", ItemType.Gloves, ItemQuality.Legendary);
        RandomItem legendaryArmor = new("Legendary Armor", ItemType.Armor, ItemQuality.Legendary);
        RandomItem legendarySword = new("Legendary Sword", ItemType.WeaponRightHand, ItemQuality.Legendary);
        RandomItem legendaryHammer = new("Legendary Hammer", ItemType.WeaponRightHand, ItemQuality.Legendary);
        RandomItem legendaryLeggings = new("Legendary Leggings", ItemType.Leggings, ItemQuality.Legendary);
        RandomItem legendaryBelt = new("Legendary Belt", ItemType.Belt, ItemQuality.Legendary);
        RandomItem legendaryHelmet = new("Legendary Helmet", ItemType.Helmet, ItemQuality.Legendary);
        RandomItem legendaryShoulders = new("Legendary Shoulders", ItemType.Shoulders, ItemQuality.Legendary);
        RandomItem legendaryBoots = new("Legendary Boots", ItemType.Boots, ItemQuality.Legendary);
        RandomItem legendaryHook = new("Legendary Hook", ItemType.WeaponLeftHand, ItemQuality.Legendary);

        // AMULETS Normal/noPrefix
        Amulet amulet1a = new("Mystic Amulet");
        Amulet amulet2a = new("Mysterious Amulet");
        Amulet amulet3a = new("Millennium Amulet");
        Amulet amulet4a = new("Mythic Amulet");
        // AMULETS Magic
        Amulet amulet1b = new("Magic Amulet", "Magic");
        // AMULETS Rare
        Amulet amulet1c = new("Shiny Amulet", "Rare");
        Amulet amulet2c = new("Rare Amulet", "Rare");
        Amulet amulet3c = new("Golden Amulet", "Rare");
        Amulet amulet4c = new("Sparkling Amulet", "Rare");
        Amulet amulet5c = new("Shimmering Amulet", "Rare");
        Amulet amulet6c = new("Sun Amulet", "Rare");
        Amulet amulet7c = new("Moon Amulet", "Rare");
        Amulet amulet8cc = new("Amulet of Gold", "Rare");
        Amulet amulet9cc = new("Amulet of Silver", "Rare");
        // AMULETS Epic
        Amulet amulet8c = new("Epic Amulet", "Epic");
        Amulet amulet9c = new("Epic Necklace", "Epic");
        // AMULETS Legendary
        Amulet amulet10c = new("Legendary Amulet", "Legendary");
        Amulet amulet11c = new("Amulet of Legends", "Legendary");

        // ImprovedRandomItems
        ImprovedRandomItem boots1 = new(ItemType.Boots);
        ImprovedRandomItem boots2 = new(ItemType.Boots);
        ImprovedRandomItem boots3 = new(ItemType.Boots);
        ImprovedRandomItem boots4 = new(ItemType.Boots);
        ImprovedRandomItem boots5 = new(ItemType.Boots);
        ImprovedRandomItem boots6 = new(ItemType.Boots);
        ImprovedRandomItem boots7 = new(ItemType.Boots);
        ImprovedRandomItem boots8 = new(ItemType.Boots);
        ImprovedRandomItem boots9 = new(ItemType.Boots);
        ImprovedRandomItem boots10 = new(ItemType.Boots);
        ImprovedRandomItem boots11 = new(ItemType.Boots);
        ImprovedRandomItem boots12 = new(ItemType.Boots);
        ImprovedRandomItem boots13 = new(ItemType.Boots);
        ImprovedRandomItem armor1 = new(ItemType.Armor);
        ImprovedRandomItem armor2 = new(ItemType.Armor);
        ImprovedRandomItem armor3 = new(ItemType.Armor);
        ImprovedRandomItem armor4 = new(ItemType.Armor);
        ImprovedRandomItem armor5 = new(ItemType.Armor);
        ImprovedRandomItem armor6 = new(ItemType.Armor);
        ImprovedRandomItem armor7 = new(ItemType.Armor);
        ImprovedRandomItem armor8 = new(ItemType.Armor);
        ImprovedRandomItem armor9 = new(ItemType.Armor);
        ImprovedRandomItem armor10 = new(ItemType.Armor);
        ImprovedRandomItem armor11 = new(ItemType.Armor);
        ImprovedRandomItem armor12 = new(ItemType.Armor);
        ImprovedRandomItem armor13 = new(ItemType.Armor);
        ImprovedRandomItem armor14 = new(ItemType.Armor);
        ImprovedRandomItem armor15 = new(ItemType.Armor);
        ImprovedRandomItem weaponright = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright1 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright2 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright3 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright4 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright5 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright6 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright7 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright8 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright9 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright10 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright11 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright12 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem weaponright13 = new(ItemType.WeaponRightHand);
        ImprovedRandomItem gloves1 = new(ItemType.Gloves);
        ImprovedRandomItem gloves2 = new(ItemType.Gloves);
        ImprovedRandomItem gloves3 = new(ItemType.Gloves);
        ImprovedRandomItem gloves4 = new(ItemType.Gloves);
        ImprovedRandomItem gloves5 = new(ItemType.Gloves);
        ImprovedRandomItem gloves6 = new(ItemType.Gloves);
        ImprovedRandomItem gloves7 = new(ItemType.Gloves);
        ImprovedRandomItem gloves8 = new(ItemType.Gloves);
        ImprovedRandomItem gloves9 = new(ItemType.Gloves);
        ImprovedRandomItem gloves10 = new(ItemType.Gloves);
        ImprovedRandomItem gloves11 = new(ItemType.Gloves);
        ImprovedRandomItem gloves12 = new(ItemType.Gloves);
        ImprovedRandomItem gloves13 = new(ItemType.Gloves);
        ImprovedRandomItem gloves14 = new(ItemType.Gloves);
        ImprovedRandomItem belt1 = new(ItemType.Belt);
        ImprovedRandomItem belt2 = new(ItemType.Belt);
        ImprovedRandomItem belt3 = new(ItemType.Belt);
        ImprovedRandomItem belt4 = new(ItemType.Belt);
        ImprovedRandomItem belt5 = new(ItemType.Belt);
        ImprovedRandomItem belt6 = new(ItemType.Belt);
        ImprovedRandomItem belt7 = new(ItemType.Belt);
        ImprovedRandomItem belt8 = new(ItemType.Belt);
        ImprovedRandomItem belt9 = new(ItemType.Belt);
        ImprovedRandomItem belt10 = new(ItemType.Belt);
        ImprovedRandomItem belt11 = new(ItemType.Belt);
        ImprovedRandomItem belt12 = new(ItemType.Belt);
        ImprovedRandomItem belt13 = new(ItemType.Belt);
        ImprovedRandomItem belt14 = new(ItemType.Belt);
        ImprovedRandomItem belt15 = new(ItemType.Belt);
        ImprovedRandomItem shoulders1 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders2 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders3 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders4 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders5 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders6 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders7 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders8 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders9 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders10 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders11 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders12 = new(ItemType.Shoulders);
        ImprovedRandomItem shoulders13 = new(ItemType.Shoulders);
        ImprovedRandomItem amulet1 = new(ItemType.Amulet);
        ImprovedRandomItem amulet2 = new(ItemType.Amulet);
        ImprovedRandomItem amulet3 = new(ItemType.Amulet);
        ImprovedRandomItem amulet4 = new(ItemType.Amulet);
        ImprovedRandomItem helmet1 = new(ItemType.Helmet);
        ImprovedRandomItem helmet2 = new(ItemType.Helmet);
        ImprovedRandomItem helmet3 = new(ItemType.Helmet);
        ImprovedRandomItem helmet4 = new(ItemType.Helmet);
        ImprovedRandomItem helmet5 = new(ItemType.Helmet);
        ImprovedRandomItem helmet6 = new(ItemType.Helmet);
        ImprovedRandomItem helmet7 = new(ItemType.Helmet);
        ImprovedRandomItem helmet8 = new(ItemType.Helmet);
        ImprovedRandomItem helmet9 = new(ItemType.Helmet);
        ImprovedRandomItem helmet10 = new(ItemType.Helmet);
        ImprovedRandomItem helmet11 = new(ItemType.Helmet);
        ImprovedRandomItem helmet12 = new(ItemType.Helmet);
        ImprovedRandomItem leggings1 = new(ItemType.Leggings);
        ImprovedRandomItem leggings2 = new(ItemType.Leggings);
        ImprovedRandomItem leggings3 = new(ItemType.Leggings);
        ImprovedRandomItem leggings4 = new(ItemType.Leggings);
        ImprovedRandomItem leggings5 = new(ItemType.Leggings);
        ImprovedRandomItem leggings6 = new(ItemType.Leggings);
        ImprovedRandomItem leggings7 = new(ItemType.Leggings);
        ImprovedRandomItem leggings8 = new(ItemType.Leggings);
        ImprovedRandomItem hook1 = new(ItemType.WeaponLeftHand);
        ImprovedRandomItem hook2 = new(ItemType.WeaponLeftHand);
        ImprovedRandomItem hook3 = new(ItemType.WeaponLeftHand);
        ImprovedRandomItem hook4 = new(ItemType.WeaponLeftHand);
        ImprovedRandomItem hook5 = new(ItemType.WeaponLeftHand);
        ImprovedRandomItem hook6 = new(ItemType.WeaponLeftHand);

        noItems.Add(null);

        // List of items 1 (Act 1 West)
        items1.Add(boots1);
        items1.Add(boots2);
        items1.Add(boots3);
        items1.Add(armor1);
        items1.Add(armor2);
        items1.Add(armor3);
        items1.Add(gloves1);
        items1.Add(item1a);
        items1.Add(item2a);
        items1.Add(item1b);
        items1.Add(item6b);
        items1.Add(item12);
        items1.Add(item13);
        items1.Add(item14);
        items1.Add(item20);
        items1.Add(item26);
        items1.Add(item27);
        items1.Add(item28);
        items1.Add(item29);
        items1.Add(item34);
        items1.Add(item36);
        items1.Add(item37);
        items1.Add(item10c);
        items1.Add(item16bb);
        items1.Add(item17bb);
        items1.Add(weaponright);
        items1.Add(item7aa);
        items1.Add(item18bb);
        items1.Add(item19bb);
        items1.Add(item20bb);
        items1.Add(item17d);
        items1.Add(item8aa);
        items1.Add(item44);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);
        items1.Add(null);

        // List of items 2 (Act 1 East)
        items2.Add(weaponright1);
        items2.Add(weaponright2);
        items2.Add(gloves2);
        items2.Add(belt1);
        items2.Add(belt2);
        items2.Add(item1b);
        items2.Add(item2b);
        items2.Add(item3b);
        items2.Add(item4b);
        items2.Add(item5b);
        items2.Add(item7b);
        items2.Add(item8b);
        items2.Add(item9b);
        items2.Add(item1a);
        items2.Add(item3a);
        items2.Add(item4a);
        items2.Add(item5a);
        items2.Add(item6a);
        items2.Add(item10);
        items2.Add(item11);
        items2.Add(item14);
        items2.Add(item9a);
        items2.Add(item10a);
        items2.Add(item7);
        items2.Add(item8);
        items2.Add(item15);
        items2.Add(item16);
        items2.Add(item17);
        items2.Add(item18);
        items2.Add(item20);
        items2.Add(item21);
        items2.Add(item22);
        items2.Add(item28);
        items2.Add(item29);
        items2.Add(item9);
        items2.Add(item30);
        items2.Add(item33);
        items2.Add(item35);
        items2.Add(item13c);
        items2.Add(item14c);
        items2.Add(item15bb);
        items2.Add(item38);
        items2.Add(belt13);
        items2.Add(item41);
        items2.Add(item42);
        items2.Add(item18d);
        items2.Add(item43);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);
        items2.Add(null);

        // List of items 3 SNOW
        items3.Add(item6a);
        items3.Add(item7a);
        items3.Add(item8a);
        items3.Add(item2b);
        items3.Add(item10b);
        items3.Add(item11b);
        items3.Add(item12b);
        items3.Add(item13b);
        items3.Add(item14b);
        items3.Add(item15b);
        items3.Add(item7);
        items3.Add(item8);
        items3.Add(item15);
        items3.Add(item19);
        items3.Add(item18b);
        items3.Add(item24);
        items3.Add(item25);
        items3.Add(item22);
        items3.Add(item9);
        items3.Add(item30);
        items3.Add(item31);
        items3.Add(item34);
        items3.Add(item11c);
        items3.Add(item12c);
        items3.Add(item16c);
        items3.Add(item27a);
        items3.Add(weaponright3);
        items3.Add(item28a);
        items3.Add(item19);
        items3.Add(boots12);
        items3.Add(boots13);
        items3.Add(gloves13);
        items3.Add(belt9);
        items3.Add(belt10);
        items3.Add(armor11);
        items3.Add(armor12);
        items3.Add(armor13);
        items3.Add(weaponright10);
        items3.Add(belt11);
        items3.Add(belt12);
        items3.Add(shoulders13);
        items3.Add(item39);
        items3.Add(item40);
        items3.Add(item10aa);
        items3.Add(magicBelt3);
        items3.Add(item18c);
        items3.Add(item19c);
        items3.Add(item30aa);
        items3.Add(item45);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);
        items3.Add(null);

        // List of items 4 SEA Act 3
        items4.Add(item16b);
        items4.Add(item17b);
        items4.Add(amulet1b);
        items4.Add(item11a);
        items4.Add(item18b);
        items4.Add(item19b);
        items4.Add(item20b);
        items4.Add(item21b);
        items4.Add(item12a);
        items4.Add(item26a);
        items4.Add(item33b);
        items4.Add(gloves4);
        items4.Add(gloves5);
        items4.Add(gloves6);
        items4.Add(shoulders1);
        items4.Add(shoulders2);
        items4.Add(shoulders3);
        items4.Add(item15d);
        items4.Add(item16d);
        items4.Add(amulet2c);
        items4.Add(helmet1);
        items4.Add(helmet2);
        items4.Add(item29a);
        items4.Add(shoulders10);
        items4.Add(weaponright11);
        items4.Add(weaponright12);
        items4.Add(weaponright13);
        items4.Add(belt15);
        items4.Add(belt14);
        items4.Add(epicArmor1);
        items4.Add(helmet9);
        items4.Add(leggings7);
        items4.Add(shoulders11);
        items4.Add(shoulders12);
        items4.Add(armor14);
        items4.Add(helmet11);
        items4.Add(helmet12);
        items4.Add(item17c);
        items4.Add(item38b);
        items4.Add(item39b);
        items4.Add(magicBoots3);
        items4.Add(magicWeapon3);
        items4.Add(item40b);
        items4.Add(magicItem46);
        items4.Add(magicBoots4);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);
        items4.Add(null);

        // List of items 5 Act 4 west weak
        items5.Add(item21b);
        items5.Add(item22b);
        items5.Add(item23b);
        items5.Add(item24b);
        items5.Add(item25a);
        items5.Add(item26b);
        items5.Add(item27b);
        items5.Add(item28b);
        items5.Add(item29b);
        items5.Add(item30b);
        items5.Add(item31b);
        items5.Add(item32b);
        items5.Add(boots4);
        items5.Add(boots5);
        items5.Add(boots6);
        items5.Add(item30a);
        items5.Add(item34b);
        items5.Add(item35b);
        items5.Add(item36b);
        items5.Add(item37b);
        items5.Add(leggings8);
        items5.Add(helmet10);
        items5.Add(magicShoulders3);
        items5.Add(rareShoulders1);
        items5.Add(rareBoots1);
        items5.Add(gloves14);
        items5.Add(armor15);
        items5.Add(item29aa);
        items5.Add(rareShoulders2);
        items5.Add(item47);
        items5.Add(magicBoots5);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);
        items5.Add(null);

        // List of Items Dragons Act4
        items6.Add(amulet1c);
        items6.Add(amulet2c);
        items6.Add(amulet3c);
        items6.Add(amulet4c);
        items6.Add(item13a);
        items6.Add(amulet1);
        items6.Add(amulet2);
        items6.Add(amulet3);
        items6.Add(amulet4);
        items6.Add(amulet5c);
        items6.Add(amulet6c);
        items6.Add(amulet7c);
        items6.Add(amulet8c);
        items6.Add(amulet9c);
        items6.Add(amulet10c);
        items6.Add(rareBoots2);
        items6.Add(epicArmor3);
        items6.Add(epicBelt3);
        items6.Add(epicHelmet3);
        items6.Add(amulet8cc);
        items6.Add(amulet11c);
        items6.Add(amulet9cc);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);
        items6.Add(null);

        // Act 5 Gloves, Armor, weaponsRight, Leggings, Belt
        items7.Add(legendaryGloves);
        items7.Add(legendaryArmor);
        items7.Add(legendarySword);
        items7.Add(legendaryLeggings);
        items7.Add(legendaryBelt);
        items7.Add(epicGloves1);
        items7.Add(epicGloves2);
        items7.Add(epicArmor1);
        items7.Add(epicArmor2);
        items7.Add(epicSword1);
        items7.Add(epicSword2);
        items7.Add(epicLeggings1);
        items7.Add(epicLeggings2);
        items7.Add(epicBelt1);
        items7.Add(epicBelt2);
        items7.Add(gloves7);
        items7.Add(gloves8);
        items7.Add(gloves9);
        items7.Add(gloves10);
        items7.Add(gloves11);
        items7.Add(gloves12);
        items7.Add(armor5);
        items7.Add(armor6);
        items7.Add(armor7);
        items7.Add(armor8);
        items7.Add(armor9);
        items7.Add(armor10);
        items7.Add(weaponright4);
        items7.Add(weaponright5);
        items7.Add(weaponright6);
        items7.Add(weaponright7);
        items7.Add(weaponright8);
        items7.Add(weaponright9);
        items7.Add(leggings1);
        items7.Add(leggings2);
        items7.Add(leggings3);
        items7.Add(leggings4);
        items7.Add(leggings5);
        items7.Add(leggings6);
        items7.Add(belt3);
        items7.Add(belt4);
        items7.Add(belt5);
        items7.Add(belt6);
        items7.Add(belt7);
        items7.Add(belt8);
        items7.Add(magicLeggings1);
        items7.Add(magicLeggings2);
        items7.Add(magicArmor1);
        items7.Add(magicArmor2);
        items7.Add(magicBelt1);
        items7.Add(magicBelt2);
        items7.Add(magicWeapon1);
        items7.Add(magicWeapon2);
        items7.Add(magicGloves1);
        items7.Add(magicGloves2);
        items7.Add(epicArmor4);
        items7.Add(legendaryHammer);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);
        items7.Add(null);

        // Act 5 Helmets, Shoulders, Boots, weaponsLeft
        items8.Add(legendaryHelmet);
        items8.Add(legendaryShoulders);
        items8.Add(legendaryBoots);
        items8.Add(legendaryHook);
        items8.Add(epicHelmet1);
        items8.Add(epicHelmet2);
        items8.Add(epicShoulders1);
        items8.Add(epicShoulders2);
        items8.Add(epicBoots1);
        items8.Add(epicBoots2);
        items8.Add(epicHook1);
        items8.Add(epicHook2);
        items8.Add(helmet3);
        items8.Add(helmet4);
        items8.Add(helmet5);
        items8.Add(helmet6);
        items8.Add(helmet7);
        items8.Add(helmet8);
        items8.Add(shoulders4);
        items8.Add(shoulders5);
        items8.Add(shoulders6);
        items8.Add(shoulders7);
        items8.Add(shoulders8);
        items8.Add(shoulders9);
        items8.Add(boots6);
        items8.Add(boots7);
        items8.Add(boots8);
        items8.Add(boots9);
        items8.Add(boots10);
        items8.Add(boots11);
        items8.Add(hook1);
        items8.Add(hook2);
        items8.Add(hook3);
        items8.Add(hook4);
        items8.Add(hook5);
        items8.Add(hook6);
        items8.Add(magicShoulders1);
        items8.Add(magicShoulders2);
        items8.Add(magicBoots1);
        items8.Add(magicBoots2);
        items8.Add(magicHook1);
        items8.Add(magicHook2);
        items8.Add(magicHelmet1);
        items8.Add(magicHelmet2);
        items8.Add(epicHelmet4);
        items8.Add(epicHook3);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);
        items8.Add(null);

        // List of Boss Godly items
        godlyBossItems.Add(new RandomItem("Godly Mace", ItemType.WeaponRightHand, ItemQuality.Godly));
        godlyBossItems.Add(new RandomItem("Godly Claw", ItemType.WeaponLeftHand, ItemQuality.Godly));
        godlyBossItems.Add(new RandomItem("Godly Guards", ItemType.Gloves, ItemQuality.Godly));
        godlyBossItems.Add(new Amulet("Godly Necklage", "Legendary"));
        godlyBossItems.Add(new RandomItem("Godly Spaulders", ItemType.Shoulders, ItemQuality.Godly));
        godlyBossItems.Add(new RandomItem("Godly Crest", ItemType.Helmet, ItemQuality.Godly));
        godlyBossItems.Add(new RandomItem("Godly Mail", ItemType.Armor, ItemQuality.Godly));
        godlyBossItems.Add(new RandomItem("Godly Greaves", ItemType.Leggings, ItemQuality.Godly));
        godlyBossItems.Add(new RandomItem("Godly Walkers", ItemType.Boots, ItemQuality.Godly));

        // List of weak amulets
        weakAmulets.Add(amulet1a);
        weakAmulets.Add(amulet2a);
        weakAmulets.Add(amulet3a);
        weakAmulets.Add(amulet4a);
        weakAmulets.Add(null);
        weakAmulets.Add(null);
        weakAmulets.Add(null);
        weakAmulets.Add(null);
        // List of magic amulets
        magicAmulets.Add(amulet1b);
        // List of rare amulets
        rareAmulets.Add(amulet1c);
        rareAmulets.Add(amulet2c);
    }

}